/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Actualité;

import gestion_university.JDBC;
import static gestion_university.JDBC.conn;
import static gestion_university.JDBC.rs;
import static gestion_university.JDBC.stmt;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AbdoU
 */
public class modif_Actuality extends javax.swing.JFrame {

    /**
     * Creates new form modif_Actuality
     */
    public modif_Actuality() {
        initComponents();
        setSize( 800, 500 );
        setLocation(545, 260);
        this.setDefaultCloseOperation(2);
        
        try{
            
            JDBC DB = new JDBC();
            DB.connection();
            
            String sqlE ;
            sqlE = "select * from actuality";
            rs = stmt.executeQuery(sqlE);
            
           
            while(rs.next()){
                System.out.println(rs.getRow());
                String TITRE_ACTU = rs.getString("TITRE_ACTU");
                      
                String tabDataEv[] = {TITRE_ACTU};
                DefaultTableModel tabModelEv = (DefaultTableModel)tableActuM.getModel();
                tabModelEv.addRow(tabDataEv);
              
            }
            
            stmt.close();
            rs.close();
            conn.close();
        }catch(SQLException e){
            System.out.println("erreur "+e);
        }
        
        
    }

     private void getFromTable(){
        int r = tableActuM.getSelectedRow();
        r=r+1;
        JDBC db=new JDBC();
        db.connection();
        String sqlActu="SELECT * FROM actuality WHERE ID_ACTU="+r;
        try {
            
            rs=stmt.executeQuery(sqlActu);
            while(rs.next()){
                
                String TITRE_Actu = rs.getString("TITRE_ACTU");
                String DATE_DActu  = rs.getString("DATE_J_D_ACTU");
                String DATE_FActu  = rs.getString("DATE_J_F_ACTU");
                String HEURE_Actu = rs.getString("HEURE_F_ACTU");
                String LINK_Actu = rs.getString("LINK_ACTU");
                String TEXT_Actu  = rs.getString("TEXT_ACTU");
                
                String[] arrOfStr1M = DATE_DActu.split(" ", 2);
                DATE_DActu = arrOfStr1M[0];
                String[] arrOfStr2M = DATE_FActu.split(" ", 2);
                DATE_FActu = arrOfStr2M[0];
                
                descrActuM.setText(TEXT_Actu);
                titreActuM.setText(TITRE_Actu);
                dateD.setText(DATE_DActu);
                dateF.setText(DATE_FActu);
                heurD.setText(HEURE_Actu);
                link.setText(LINK_Actu);
            }
            rs.close();
            stmt.close();
            conn.close();
        }
        catch (SQLException ex) {
            System.out.println("erreur"+ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableActuM = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descrActuM = new javax.swing.JTextPane();
        titreActuM = new javax.swing.JTextField();
        dateD = new javax.swing.JTextField();
        dateF = new javax.swing.JTextField();
        heurD = new javax.swing.JTextField();
        link = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tableActuM.setForeground(new java.awt.Color(102, 0, 51));
        tableActuM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                           Titre d'actualité"
            }
        ));
        tableActuM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableActuMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableActuM);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 70, 360, 120);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText("Date fin                         :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 280, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Date début                   :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 240, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Link                                :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 360, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Heur début                   :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 320, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Titre                              :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 200, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("Descreption d'évenement :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 70, 190, 30);

        descrActuM.setToolTipText("");
        jScrollPane2.setViewportView(descrActuM);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(370, 100, 380, 90);
        getContentPane().add(titreActuM);
        titreActuM.setBounds(540, 200, 210, 30);
        getContentPane().add(dateD);
        dateD.setBounds(540, 240, 210, 30);
        getContentPane().add(dateF);
        dateF.setBounds(540, 280, 210, 30);
        getContentPane().add(heurD);
        heurD.setBounds(540, 320, 210, 30);
        getContentPane().add(link);
        link.setBounds(540, 360, 210, 30);

        jButton2.setBackground(new java.awt.Color(189, 255, 207));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Valider");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 410, 130, 40);

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(660, 410, 110, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Modifier actualité");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 0, 280, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/actu.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 780, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableActuMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableActuMMouseClicked
        // TODO add your handling code here:
        getFromTable();
    }//GEN-LAST:event_tableActuMMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int ID = tableActuM.getSelectedRow();
        ID=ID+1;
        System.out.println("ID ==> "+ID);
        String EvDescreption = descrActuM.getText();
        String EvTitre = titreActuM.getText();
        String EvDateDeb = dateD.getText();
        String EvDateFin= dateF.getText();
        String EvHeurDib = heurD.getText();
        String Link = link.getText();

        System.out.println(EvDateDeb);
        System.out.println(EvDateFin);

        JDBC db=new JDBC();
        db.connection();
        try{

            if(EvDescreption.length()!=0 && EvTitre.length()!=0 && EvDateDeb.length()!=0 &&
                EvDateFin.length()!=0 && EvHeurDib.length()!=0 && Link.length()!=0){

                String sq = "update actuality set TITRE_ACTU = '"+EvTitre+"', "
                + "DATE_J_D_ACTU = TO_DATE('"+EvDateDeb+"', 'YYYY-MM-DD'), "
                + "DATE_J_F_ACTU = TO_DATE('"+EvDateFin+"', 'YYYY-MM-DD'),"
                + "HEURE_F_ACTU = '"+EvHeurDib+"', LINK_ACTU = '"+Link+"', "
                + "TEXT_ACTU = '"+EvDescreption+"' WHERE ID_ACTU = "+ID;
                System.out.println(sq);
                stmt.executeUpdate(sq);
                this.setVisible(false);
                new modif_Actuality().setVisible(true);

            }
        }catch(SQLException exp){
            System.out.println("ErreurT"+exp);
        }
        finally{
            try{
                rs.close();
                stmt.close();
                conn.close();
            }
            catch(SQLException e){
                System.out.println("Erreur"+e);
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int response= JOptionPane.showConfirmDialog(null, "Do you really want to Quit?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response== JOptionPane.NO_OPTION) {
            new modif_Actuality().setVisible(false);
        } else if (response== JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modif_Actuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modif_Actuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modif_Actuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modif_Actuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modif_Actuality().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateD;
    private javax.swing.JTextField dateF;
    private javax.swing.JTextPane descrActuM;
    private javax.swing.JTextField heurD;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField link;
    private javax.swing.JTable tableActuM;
    private javax.swing.JTextField titreActuM;
    // End of variables declaration//GEN-END:variables
}
