/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Actualité;

import gestion_university.JDBC;
import static gestion_university.JDBC.conn;
import static gestion_university.JDBC.rs;
import static gestion_university.JDBC.stmt;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class supp_Actuality extends javax.swing.JFrame {

    /**
     * Creates new form supp_Actuality
     */
    public supp_Actuality() {
        initComponents();
        setSize( 800, 500 );
        setLocation(545, 260);
        this.setDefaultCloseOperation(2);
        
        
        try{
            
            JDBC DB = new JDBC();
            DB.connection();
//            int r = tableEventS.getSelectedRow();
//            r=r+1;
            String sqlE ;
            sqlE = "select * from actuality";
            rs = stmt.executeQuery(sqlE);
            
           
            while(rs.next()){
                System.out.println(rs.getRow());
                String TITRE_EVE = rs.getString("TITRE_ACTU");
                      
                String tabDataEvS[] = {TITRE_EVE};
                DefaultTableModel tabModelEvS = (DefaultTableModel)tableActuS.getModel();
                tabModelEvS.addRow(tabDataEvS);
              
            }
            
            stmt.close();
            rs.close();
            conn.close();
        }catch(SQLException e){
            System.out.println("erreur "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableActuS = new javax.swing.JTable();
        titreActuS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tableActuS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                                           Titre d'actuality"
            }
        ));
        tableActuS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableActuSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableActuS);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 80, 560, 220);
        getContentPane().add(titreActuS);
        titreActuS.setBounds(200, 310, 340, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("Titre      :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 310, 80, 30);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 310, 120, 30);

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(660, 410, 110, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Suppression d'actualité");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 0, 230, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/actu.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 780, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableActuSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableActuSMouseClicked
        // TODO add your handling code here:
        int r = tableActuS.getSelectedRow();
        
        String val = tableActuS.getModel().getValueAt(r, 0).toString();
        JDBC db=new JDBC();
        db.connection();
        String sqlEv="SELECT TITRE_ACTU FROM actuality where TITRE_ACTU = '"+val+"'";
        try {
            rs=stmt.executeQuery(sqlEv);
            while(rs.next()){
                
                titreActuS.setText(rs.getString("TITRE_ACTU"));
                
                }
                rs.close();
                stmt.close();
                conn.close();
            }
            catch (SQLException ex) {
                System.out.println("erreur"+ex);
            }
    }//GEN-LAST:event_tableActuSMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String ActuTitreS = titreActuS.getText();
        JDBC db=new JDBC();
        
        db.connection();
        try{
            PreparedStatement ps = conn.prepareStatement("DELETE FROM actuality WHERE TITRE_ACTU = '"+ActuTitreS+"'"); 
            ps.executeUpdate();
            this.setVisible(false);
            new supp_Actuality().setVisible(true);
        }catch(SQLException exp){
            System.out.println("ErreurT"+exp);
        }
        finally{
            try{
                rs.close();
                stmt.close();
                conn.close();
            }
            catch(SQLException e){
                System.out.println("Erreur"+e);
            }
             
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int response= JOptionPane.showConfirmDialog(null, "Do you really want to Quit?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response== JOptionPane.NO_OPTION) {
            new supp_Actuality().setVisible(false);
        } else if (response== JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supp_Actuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supp_Actuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supp_Actuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supp_Actuality.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supp_Actuality().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableActuS;
    private javax.swing.JTextField titreActuS;
    // End of variables declaration//GEN-END:variables
}
