/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Etablissement;

import gestion_university.JDBC;
import gestion_university.affiche_messages;
import static gestion_university.JDBC.rs;
import static gestion_university.JDBC.stmt;
import javax.swing.JOptionPane;

/**
 *
 * @author walid
 */
public class Ajouter_etablissement extends javax.swing.JFrame {

    /**
     * Creates new form Ajouter_etablissement
     */
    public Ajouter_etablissement() {
        initComponents();
        setLocation(545, 260);
        setSize(800,500);
        this.setDefaultCloseOperation(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        abre_eta = new javax.swing.JTextField();
        nom_eta = new javax.swing.JTextField();
        adresse_eta = new javax.swing.JTextField();
        tele_eta = new javax.swing.JTextField();
        email_eta = new javax.swing.JTextField();
        link_eta = new javax.swing.JTextField();
        photo_eta = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajouter établissement");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 0, 460, 70);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("ADRESSE_ESTA : ");
        jLabel4.setPreferredSize(new java.awt.Dimension(90, 30));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("TELE_ESTA : ");
        jLabel5.setPreferredSize(new java.awt.Dimension(90, 30));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 210, 140, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("EMAIL_ESTA : ");
        jLabel6.setPreferredSize(new java.awt.Dimension(90, 30));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 250, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("LINK_ESTA : ");
        jLabel7.setPreferredSize(new java.awt.Dimension(90, 30));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 290, 140, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("PHOTO_ESTA : ");
        jLabel8.setPreferredSize(new java.awt.Dimension(90, 30));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 330, 140, 30);

        abre_eta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abre_etaActionPerformed(evt);
            }
        });
        getContentPane().add(abre_eta);
        abre_eta.setBounds(210, 90, 430, 30);
        getContentPane().add(nom_eta);
        nom_eta.setBounds(210, 130, 430, 30);
        getContentPane().add(adresse_eta);
        adresse_eta.setBounds(210, 170, 430, 30);
        getContentPane().add(tele_eta);
        tele_eta.setBounds(210, 210, 430, 30);
        getContentPane().add(email_eta);
        email_eta.setBounds(210, 250, 430, 30);
        getContentPane().add(link_eta);
        link_eta.setBounds(210, 290, 430, 30);
        getContentPane().add(photo_eta);
        photo_eta.setBounds(210, 330, 430, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel11.setText("ABRE_ESTA :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 90, 140, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 204));
        jLabel12.setText("NOM_ESTA :");
        jLabel12.setPreferredSize(new java.awt.Dimension(90, 30));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 130, 140, 30);

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("Ajouter Filière et Prof");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 410, 200, 40);

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(670, 410, 110, 40);

        jButton5.setBackground(new java.awt.Color(189, 255, 207));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setText("Enregistrer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(60, 410, 240, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ucaav1.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(800, 550));
        jLabel2.setRequestFocusEnabled(false);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 810, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abre_etaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abre_etaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abre_etaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int response= JOptionPane.showConfirmDialog(null, "Do you really want to Quit?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response== JOptionPane.NO_OPTION) {
            new affiche_messages().setVisible(false);
        } else if (response== JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String ab=abre_eta.getText().toString();
        String nom=nom_eta.getText().toString();
        String ad=adresse_eta.getText().toString();
        String tele=tele_eta.getText().toString();
        String email=email_eta.getText().toString();
        String link=link_eta.getText().toString();
        String img=photo_eta.getText().toString();
        int id = -10000;
        
        JDBC db=new JDBC();
        db.connection();
        
        try{
            String query="select * from establishment ";
            rs=stmt.executeQuery(query);
            while(rs.next()){
                id=rs.getRow()+1;
            }
            if(ab.length()!=0 && nom.length()!=0 && ad.length()!=0 && tele.length()!=0 && email.length()!=0 && link.length()!=0 && img.length()!=0){
                String q="INSERT INTO establishment VALUES ("+id+",'"+ab+"',upper('"+nom+"'),'"+ad+"','"+tele+"','"+email+"','"+link+"','"+img+".png')";
                stmt.executeUpdate(q);
            }
        }catch(Exception exp){
            System.out.println("ErreurT"+exp);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Ajouter_Filière_prof().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajouter_etablissement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajouter_etablissement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajouter_etablissement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajouter_etablissement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajouter_etablissement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abre_eta;
    private javax.swing.JTextField adresse_eta;
    private javax.swing.JTextField email_eta;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField link_eta;
    private javax.swing.JTextField nom_eta;
    private javax.swing.JTextField photo_eta;
    private javax.swing.JTextField tele_eta;
    // End of variables declaration//GEN-END:variables
}
