/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Etablissement;

import Main.JDBC;
import static Main.JDBC.conn;
import static Main.JDBC.rs;
import static Main.JDBC.stmt;
import java.sql.ResultSet;

import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author walid
 */
public class modifier_Filière_prof extends javax.swing.JFrame {
    public static String abre_f;
    public static String nom_f;
    public static String nom_pr;
    public static String prenom_pr;
    public static String email_pr;
    /**
     * Creates new form modifier_Filière_prof
     */
    public modifier_Filière_prof() {
        initComponents();
        setLocation(545, 260);
        setSize(800,500);
        this.setDefaultCloseOperation(2);
        try{
            JDBC DB = new JDBC();
            DB.connection();
            String sq = "SELECT ABRE_ESTA,NOM_ESTA FROM establishment";
            rs = stmt.executeQuery(sq);

            while(rs.next()){
                String abre = rs.getString("ABRE_ESTA");
                String nom = rs.getString("NOM_ESTA");
                
                String tabData[] = {abre, nom};
                DefaultTableModel tabModel = (DefaultTableModel)tableeta.getModel();
                tabModel.addRow(tabData);
            
            }
            
            stmt.close();
            rs.close();
            conn.close();
        }
        catch(SQLException e){
            System.out.println("erreur "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableprof = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableeta = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablefiliere = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        nom_fil = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        abre_fil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nom_prof = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        prenom_prof = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        email_prof = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modifier les Filières et les Profs");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 0, 420, 40);

        tableprof.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom_Professeur", "Prenom_professeur", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableprof.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableprofMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableprof);
        if (tableprof.getColumnModel().getColumnCount() > 0) {
            tableprof.getColumnModel().getColumn(0).setMinWidth(80);
            tableprof.getColumnModel().getColumn(0).setMaxWidth(130);
            tableprof.getColumnModel().getColumn(1).setMinWidth(80);
            tableprof.getColumnModel().getColumn(1).setMaxWidth(140);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(480, 210, 300, 160);

        tableeta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Abréviation", "Nom Etablissement"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableetaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableeta);
        if (tableeta.getColumnModel().getColumnCount() > 0) {
            tableeta.getColumnModel().getColumn(0).setMinWidth(80);
            tableeta.getColumnModel().getColumn(0).setMaxWidth(89);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(480, 40, 300, 150);

        tablefiliere.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Abréviation Filière", "Nom Filière "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablefiliere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablefiliereMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablefiliere);
        if (tablefiliere.getColumnModel().getColumnCount() > 0) {
            tablefiliere.getColumnModel().getColumn(0).setMinWidth(80);
            tablefiliere.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 40, 460, 150);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setText("Abréviation Filière : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 190, 150, 40);

        nom_fil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_filActionPerformed(evt);
            }
        });
        getContentPane().add(nom_fil);
        nom_fil.setBounds(170, 240, 190, 30);

        jButton1.setBackground(new java.awt.Color(189, 255, 207));
        jButton1.setText("Modifier la Filière");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 270, 150, 30);

        jButton2.setBackground(new java.awt.Color(189, 255, 207));
        jButton2.setText("Modifier Professeur");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 430, 150, 30);

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(690, 420, 100, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("Nom Filière : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 230, 110, 30);
        getContentPane().add(abre_fil);
        abre_fil.setBounds(170, 200, 190, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 153));
        jLabel6.setText("NOM_PROF : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 310, 130, 30);
        getContentPane().add(nom_prof);
        nom_prof.setBounds(170, 310, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 153));
        jLabel7.setText("PRENOM_PROF :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 350, 130, 30);
        getContentPane().add(prenom_prof);
        prenom_prof.setBounds(170, 350, 190, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 153));
        jLabel8.setText("EMAIL_PROF : ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 390, 120, 30);
        getContentPane().add(email_prof);
        email_prof.setBounds(170, 390, 190, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ucaav1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableprofMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableprofMouseClicked
        int r = tableprof.getSelectedRow();
        nom_prof.setText(tableprof.getValueAt(r,0).toString());
        prenom_prof.setText(tableprof.getValueAt(r,1).toString());
        email_prof.setText(tableprof.getValueAt(r,2).toString());
        
        nom_pr=tableprof.getValueAt(r,0).toString();
        prenom_pr=tableprof.getValueAt(r,1).toString();
        email_pr=tableprof.getValueAt(r,2).toString();
    }//GEN-LAST:event_tableprofMouseClicked

    private void tableetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableetaMouseClicked
        int r = tableeta.getSelectedRow();
        r=r+1;
        DefaultTableModel dm = (DefaultTableModel)tablefiliere.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
        DefaultTableModel dmp = (DefaultTableModel)tableprof.getModel();
        dmp.getDataVector().removeAllElements();
        dmp.fireTableDataChanged();
        try{
            JDBC DB = new JDBC();
            DB.connection();
            String sql="SELECT * FROM filiere WHERE ID_ESTA="+r;
            rs = stmt.executeQuery(sql);
            
            while(rs.next()){
                String abre_f = rs.getString("ABRE_FILIERE");
                String nom_f = rs.getString("NOM_FILIERE");
                
                String tabData[] = {abre_f,nom_f};
                DefaultTableModel tabModel = (DefaultTableModel)tablefiliere.getModel();
                tabModel.addRow(tabData);
            }
            rs=null;
            
            String sq="SELECT * FROM professeur WHERE ID_ESTA="+r;
            rs=stmt.executeQuery(sq);
            while(rs.next()){
               
                String nom_p = rs.getString("NOM_PROF");
                String prenom_p = rs.getString("PRENOM_PROF");
                String email_p = rs.getString("EMAIL_PROF");
                
                String tabData[] = {nom_p,prenom_p,email_p};
                DefaultTableModel tabModel = (DefaultTableModel)tableprof.getModel();
                tabModel.addRow(tabData);
                
            }
            rs.close();
            stmt.close();
            conn.close();
            
        }
        catch(SQLException e){
            System.out.println("erreur 11"+e);
        }
        
    }//GEN-LAST:event_tableetaMouseClicked

    private void tablefiliereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablefiliereMouseClicked
        int r = tablefiliere.getSelectedRow();
        abre_fil.setText(tablefiliere.getValueAt(r,0).toString());
        nom_fil.setText(tablefiliere.getValueAt(r,1).toString());
        abre_f=tablefiliere.getValueAt(r,0).toString();
        nom_f=tablefiliere.getValueAt(r,1).toString();
        
    }//GEN-LAST:event_tablefiliereMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String abfil=abre_fil.getText();
        String nomfil=nom_fil.getText();
        try{
            JDBC DB = new JDBC();
            DB.connection();
            if(abfil.length()!=0 && nomfil.length()!=0){
                String q="UPDATE filiere SET ABRE_FILIERE='"+abfil+"',NOM_FILIERE='"+nomfil+"'WHERE ABRE_FILIERE='"+abre_f+"'AND NOM_FILIERE='"+nom_f+"'";
                stmt.executeUpdate(q);
                JOptionPane dialogue = new JOptionPane("La filière est bien enregistré", JOptionPane.INFORMATION_MESSAGE);
                JDialog boîte = dialogue.createDialog("Message");
                boîte.setVisible(true);
                abre_fil.setText("");
                nom_fil.setText("");
                this.setVisible(false);
                new modifier_Filière_prof().setVisible(true);
            }
            stmt.close();
            conn.close();
        }
        catch(SQLException e){
            System.out.println("erreur "+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nom_filActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_filActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_filActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        int response= JOptionPane.showConfirmDialog(null, "Do you really want to Quit?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response== JOptionPane.NO_OPTION) {
            new modifier_Filière_prof().setVisible(false);
        } else if (response== JOptionPane.YES_OPTION) {
            this.setVisible(false);
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nom_p=nom_prof.getText();
        String prenom_p=prenom_prof.getText();
        String email_p=email_prof.getText();
        
        try{
            JDBC DB = new JDBC();
            DB.connection();
            if(nom_p.length()!=0 && prenom_p.length()!=0 && email_p.length()!=0){
                String q="UPDATE professeur SET NOM_PROF='"+nom_p+"',PRENOM_PROF='"+prenom_p+"',EMAIL_PROF='"+email_p+"' WHERE NOM_PROF='"+nom_pr+"'AND PRENOM_PROF='"+prenom_pr+"'AND EMAIL_PROF='"+email_pr+"'";
                stmt.executeUpdate(q);
                JOptionPane dialogue = new JOptionPane("Le professeur est bien enregistré", JOptionPane.INFORMATION_MESSAGE);
                JDialog boîte = dialogue.createDialog("Message");
                boîte.setVisible(true);
                nom_prof.setText("");
                prenom_prof.setText("");
                email_prof.setText("");
                
            }
            stmt.close();
            conn.close();
        }
        catch(SQLException e){
            System.out.println("erreur "+e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifier_Filière_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifier_Filière_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifier_Filière_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifier_Filière_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifier_Filière_prof().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abre_fil;
    private javax.swing.JTextField email_prof;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nom_fil;
    private javax.swing.JTextField nom_prof;
    private javax.swing.JTextField prenom_prof;
    private javax.swing.JTable tableeta;
    private javax.swing.JTable tablefiliere;
    private javax.swing.JTable tableprof;
    // End of variables declaration//GEN-END:variables
}
