/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;


import Messages.Admin_space;
import Main.*;
import static Main.JDBC.conn;
import static Main.JDBC.rs;
import static Main.JDBC.stmt;
import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author walid
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(700,518);
        setLocation(600, 280);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tlogin = new javax.swing.JTextField();
        bsign = new javax.swing.JButton();
        bclean = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Login         :");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 330, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Password :");
        jLabel2.setPreferredSize(new java.awt.Dimension(30, 16));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 370, 110, 30);

        tlogin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tlogin.setPreferredSize(new java.awt.Dimension(70, 20));
        tlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tloginActionPerformed(evt);
            }
        });
        getContentPane().add(tlogin);
        tlogin.setBounds(520, 330, 170, 30);

        bsign.setBackground(new java.awt.Color(189, 255, 207));
        bsign.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bsign.setText("Sign-in");
        bsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsignActionPerformed(evt);
            }
        });
        bsign.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bsignKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bsignKeyTyped(evt);
            }
        });
        getContentPane().add(bsign);
        bsign.setBounds(560, 430, 130, 40);

        bclean.setBackground(new java.awt.Color(255, 204, 204));
        bclean.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bclean.setText("Clean");
        bclean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcleanActionPerformed(evt);
            }
        });
        getContentPane().add(bclean);
        bclean.setBounds(471, 430, 80, 40);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gestion d'université ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 20, 260, 50);

        tpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tpasswordKeyTyped(evt);
            }
        });
        getContentPane().add(tpassword);
        tpassword.setBounds(520, 370, 170, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/login.jpeg"))); // NOI18N
        jLabel3.setRequestFocusEnabled(false);
        jLabel3.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 700, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tloginActionPerformed

    private void bsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsignActionPerformed
        String login=tlogin.getText();
        String password=tpassword.getText();
        
        JDBC db=new JDBC();
        db.connection();
        int a=0;
        try{
            String sql = "select * from administrateur where LOGIN_ADMIN='"+login+"'and PASSWORD_ADMIN='"+password+"'" ;
            rs = stmt.executeQuery(sql);
            
            while(rs.next()) {
                a=rs.getRow();
            }
            if(a==1){
                //call JFrame
                this.setVisible(false);
                Admin_space a_sp=new Admin_space();
                a_sp.setVisible(true);   
            }
            else{
                
                JOptionPane dialogue = new JOptionPane("The login or password you entered is incorrect.Please try again", JOptionPane.INFORMATION_MESSAGE);
                JDialog boîte = dialogue.createDialog("Incorrect Password");
                boîte.setVisible(true);
                bcleanActionPerformed(evt);
            }
        }catch(Exception exp){
            System.out.println("Erreur"+exp);
        }
        finally{
            try{
                rs.close();
                stmt.close();
                conn.close();
            }
            catch(Exception e){
                System.out.println("Erreur"+e);
            }
             
        }
    }//GEN-LAST:event_bsignActionPerformed

    private void bcleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcleanActionPerformed
        tlogin.setText("");
        tpassword.setText("");
    }//GEN-LAST:event_bcleanActionPerformed

    private void bsignKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bsignKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bsignKeyPressed

    private void bsignKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bsignKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_bsignKeyTyped

    private void tpasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tpasswordKeyTyped
        
    }//GEN-LAST:event_tpasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bclean;
    private javax.swing.JButton bsign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tlogin;
    private javax.swing.JPasswordField tpassword;
    // End of variables declaration//GEN-END:variables
}
