/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Evenement;

import gestion_university.JDBC;
import static gestion_university.JDBC.*;

import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AbdoU
 */
public class affiche_Evenement extends javax.swing.JFrame {

    /**
     * Creates new form affiche_Evenement
     */
    public affiche_Evenement() {
        initComponents();
        setSize( 800, 500 );
        setLocation(545, 260);
        this.setDefaultCloseOperation(2);
        try{
            JDBC DB = new JDBC();
            DB.connection();
            String sqlE ;
            sqlE = "select * from event";
            rs = stmt.executeQuery(sqlE);
            while(rs.next()){
                System.out.println(rs.getRow());
                String TITRE_EVE = rs.getString("TITRE_EVE");
                                
                String tabDataEv[] = {TITRE_EVE};
                DefaultTableModel tabModelEv = (DefaultTableModel)tableEvent.getModel();
                tabModelEv.addRow(tabDataEv);
            }
            
            stmt.close();
            rs.close();
            conn.close();
        }catch(SQLException e){
            System.out.println("erreur "+e);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEvent = new javax.swing.JTable();
        imgEv = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descEv = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tableEvent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                     Titre de L'Evenement"
            }
        ));
        tableEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEventMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEvent);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 310, 150);

        imgEv.setBackground(new java.awt.Color(51, 51, 51));
        imgEv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(imgEv);
        imgEv.setBounds(330, 60, 450, 150);

        descEv.setBackground(new java.awt.Color(204, 204, 204));
        descEv.setToolTipText("");
        jScrollPane2.setViewportView(descEv);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(160, 230, 450, 180);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Evénements");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 0, 310, 40);

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(670, 410, 110, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/event.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEventMouseClicked
        // TODO add your handling code here:
        int r = tableEvent.getSelectedRow();
        r=r+1;
        JDBC db=new JDBC();
        db.connection();
        String sqlEv="SELECT * FROM event WHERE ID_EVE="+r;
        try {
            rs=stmt.executeQuery(sqlEv);
            while(rs.next()){
                String date_deb = rs.getString("DATE_J_D_EVE");
                String date_fin = rs.getString("DATE_J_F_EVE");
                
                String[] arrOfStr1 = date_deb.split(" ", 2);
                date_deb = arrOfStr1[0];
                String[] arrOfStr2 = date_fin.split(" ", 2);
                date_fin = arrOfStr2[0];
                
                descEv.setText("Titre évenement :  "+rs.getString("TITRE_EVE") +"\n\n"+ "De : "+date_deb + " jusqu à " + date_fin + 
                        " a partire de " + rs.getString("HEURE_D_EVE") + " à " + rs.getString("HEURE_F_EVE")
                        +"\n\n"+"Description :"+"\n"+ rs.getString("TEXT_EVE"));
                //Icon icon;
                String IMG = rs.getString("PHOTO_EVE");
                System.out.println(IMG);
                imgEv.setIcon(new ImageIcon("C:\\Users\\walid\\OneDrive\\Bureau\\EST\\S3\\Modélisation et POO JAVA\\G.University\\Projet\\Gestion_University\\src\\media\\"+IMG));
                
            }
            rs.close();
            stmt.close();
            conn.close();
        }
        catch (SQLException ex) {
            System.out.println("erreur"+ex);
        }
    }//GEN-LAST:event_tableEventMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int response= JOptionPane.showConfirmDialog(null, "Do you really want to Quit?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response== JOptionPane.NO_OPTION) {
            new affiche_Evenement().setVisible(false);
        } else if (response== JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(affiche_Evenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(affiche_Evenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(affiche_Evenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(affiche_Evenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new affiche_Evenement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane descEv;
    private javax.swing.JLabel imgEv;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableEvent;
    // End of variables declaration//GEN-END:variables
}
