/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Evenement;

import Main.JDBC;
import static Main.JDBC.stmt;
import static Main.JDBC.rs;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.util.Calendar;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author AbdoU
 */
public class ajoutEvenement extends javax.swing.JFrame {

    /**
     * Creates new form ajoutEvenement
     */
    public ajoutEvenement() {
        initComponents();
        setSize( 800, 500 );
        setLocation(545, 260);
        this.setDefaultCloseOperation(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        titreEA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        heurDEA = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        heurFEA = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        imgEA = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descreptionEA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        dateDEA = new com.toedter.calendar.JDateChooser();
        dateFEA = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(titreEA);
        titreEA.setBounds(260, 50, 330, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 153));
        jLabel5.setText("Titre d'événement  :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 50, 190, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 153));
        jLabel6.setText("Date début              :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 90, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 153));
        jLabel7.setText("Date fin                   :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 130, 180, 30);
        getContentPane().add(heurDEA);
        heurDEA.setBounds(260, 170, 330, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 153));
        jLabel8.setText("Heur début              :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 170, 180, 30);
        getContentPane().add(heurFEA);
        heurFEA.setBounds(260, 210, 330, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 153));
        jLabel9.setText("Descreption             :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 290, 180, 30);
        getContentPane().add(imgEA);
        imgEA.setBounds(260, 250, 330, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 153));
        jLabel10.setText("Nome d'image        :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 250, 180, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 153));
        jLabel11.setText("Heur fin                   :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 210, 180, 30);

        jButton2.setBackground(new java.awt.Color(189, 255, 207));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 420, 120, 40);

        descreptionEA.setColumns(20);
        descreptionEA.setLineWrap(true);
        descreptionEA.setRows(5);
        jScrollPane1.setViewportView(descreptionEA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 290, 520, 120);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ajouter Evenement");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 0, 380, 40);

        dateDEA.setDateFormatString("dd-MMM-yyyy");
        getContentPane().add(dateDEA);
        dateDEA.setBounds(260, 90, 330, 30);

        dateFEA.setDateFormatString("dd-MMM-yyyy");
        getContentPane().add(dateFEA);
        dateFEA.setBounds(260, 130, 330, 30);

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(670, 420, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/event.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String titre = titreEA.getText();
        String dateDebut = ((JTextField)dateDEA.getDateEditor().getUiComponent()).getText();
        String dateFin = ((JTextField)dateFEA.getDateEditor().getUiComponent()).getText();
        String heurDebut = heurDEA.getText();
        String heurFin = heurFEA.getText();
        String imgEvenement = imgEA.getText()+".png";
        String descreptionEvenement = descreptionEA.getText();
        int id = 1;
        JDBC bd = new JDBC();
        bd.connection();
        
        try {
            String q = "select * from event";
            rs = stmt.executeQuery(q);
            while(rs.next()){
                id = rs.getRow()+1;
            }
                        
           if(titre.length() != 0 && dateDebut.length() != 0 && dateFin.length() != 0 && heurDebut.length() != 0 
                    && heurFin.length() != 0 && descreptionEvenement.length() != 0 && imgEvenement.length() != 0){
                String query = "INSERT INTO event VALUES ("+id+", '"+titre+"', "
                + "'"+dateDebut+"', '"+dateFin+"', '"+heurDebut+"', '"+heurFin+"', '"+descreptionEvenement+"', "
                    + "'"+imgEvenement+"')";
            stmt.executeUpdate(query);
            JOptionPane dialogue = new JOptionPane("Bien enregistré", JOptionPane.INFORMATION_MESSAGE);
            JDialog boîte = dialogue.createDialog("Message");
            boîte.setVisible(true);
            titreEA.setText("");heurDEA.setText("");heurFEA.setText("");imgEA.setText("");descreptionEA.setText("");
            }
            
        } catch (SQLException e) {
            System.out.println("erreur"+e);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int response= JOptionPane.showConfirmDialog(null, "Do you really want to Quit?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response== JOptionPane.NO_OPTION) {
            new ajoutEvenement().setVisible(false);
        } else if (response== JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajoutEvenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajoutEvenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajoutEvenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajoutEvenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajoutEvenement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateDEA;
    private com.toedter.calendar.JDateChooser dateFEA;
    private javax.swing.JTextArea descreptionEA;
    private javax.swing.JTextField heurDEA;
    private javax.swing.JTextField heurFEA;
    private javax.swing.JTextField imgEA;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTextField titreEA;
    // End of variables declaration//GEN-END:variables

    private void Date() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
