/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Evenement;

import gestion_university.JDBC;
import static gestion_university.JDBC.conn;
import static gestion_university.JDBC.rs;
import static gestion_university.JDBC.stmt;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AbdoU
 */
public class supp_Evenement extends javax.swing.JFrame {

    /**
     * Creates new form supp_Evenement
     */
    public supp_Evenement() {
        initComponents();
        setSize( 800, 500 );
        setLocation(545, 260);
        this.setDefaultCloseOperation(2);
        
        
        try{
            
            JDBC DB = new JDBC();
            DB.connection();
//            int r = tableEventS.getSelectedRow();
//            r=r+1;
            String sqlE ;
            sqlE = "select * from event";
            rs = stmt.executeQuery(sqlE);
            
           
            while(rs.next()){
                System.out.println(rs.getRow());
                String TITRE_EVE = rs.getString("TITRE_EVE");
                      
                String tabDataEvS[] = {TITRE_EVE};
                DefaultTableModel tabModelEvS = (DefaultTableModel)tableEventS.getModel();
                tabModelEvS.addRow(tabDataEvS);
              
            }
            
            stmt.close();
            rs.close();
            conn.close();
        }catch(SQLException e){
            System.out.println("erreur "+e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEventS = new javax.swing.JTable();
        titreEvS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tableEventS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                            Titre de L'Evenement"
            }
        ));
        tableEventS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEventSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEventS);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 80, 680, 220);
        getContentPane().add(titreEvS);
        titreEvS.setBounds(180, 340, 420, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Titre            :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 330, 110, 40);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 340, 130, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Suppression d'événement");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 0, 480, 50);

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(670, 410, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/event.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableEventSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEventSMouseClicked
        // TODO add your handling code here:
        int r = tableEventS.getSelectedRow();
        
        String val = tableEventS.getModel().getValueAt(r, 0).toString();
        System.out.println("c ==>  "+val);
        JDBC db=new JDBC();
        db.connection();
        String sqlEv="SELECT TITRE_EVE FROM event where TITRE_EVE = '"+val+"'";
        try {
            rs=stmt.executeQuery(sqlEv);
            while(rs.next()){
                
                titreEvS.setText(rs.getString("TITRE_EVE"));
                
                }
                rs.close();
                stmt.close();
                conn.close();
            }
            catch (SQLException ex) {
                System.out.println("erreur"+ex);
            }
    }//GEN-LAST:event_tableEventSMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String EvTitreS = titreEvS.getText();
        JDBC db=new JDBC();
        
        db.connection();
        try{
            PreparedStatement ps = conn.prepareStatement("DELETE FROM event WHERE TITRE_EVE = '"+EvTitreS+"'"); 
            ps.executeUpdate();
            this.setVisible(false);
            new supp_Evenement().setVisible(true);
        }catch(SQLException exp){
            System.out.println("ErreurT"+exp);
        }
        finally{
            try{
                rs.close();
                stmt.close();
                conn.close();
            }
            catch(SQLException e){
                System.out.println("Erreur"+e);
            }
             
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int response= JOptionPane.showConfirmDialog(null, "Do you really want to Quit?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response== JOptionPane.NO_OPTION) {
            new supp_Evenement().setVisible(false);
        } else if (response== JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supp_Evenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supp_Evenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supp_Evenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supp_Evenement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supp_Evenement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEventS;
    private javax.swing.JTextField titreEvS;
    // End of variables declaration//GEN-END:variables
}
