/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_university;

import static gestion_university.JDBC.conn;
import static gestion_university.JDBC.rs;
import static gestion_university.JDBC.stmt;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author walid
 */
public class affiche_messages extends javax.swing.JFrame {

    /**
     * Creates new form affiche_messages
     */
    public affiche_messages() {
        initComponents();
        setSize(830,530);
        setLocation(530, 340);
        this.setDefaultCloseOperation(2);
        try{
            JDBC DB = new JDBC();
            DB.connection();
            String sq = "select message.DATE_MES, sender.nom_sen, sender.prenom_sen, sender.email_sen from message, sender where message.ID_SEN = sender.ID_SEN";
            rs = stmt.executeQuery(sq);

            while(rs.next()){
                System.out.println(rs.getRow());
                String date_Msg = rs.getString("DATE_MES");
                String nom_Sender = rs.getString("NOM_SEN");
                String prenom_Sender = rs.getString("PRENOM_SEN");
                String email_Sender = rs.getString("EMAIL_SEN");
                String[] arrOfStr = date_Msg.split(" ", 2);
                date_Msg = arrOfStr[0];
                System.out.println(date_Msg + "  " + nom_Sender + "  " + prenom_Sender);
                String tabData[] = {date_Msg, nom_Sender, prenom_Sender, email_Sender};
                DefaultTableModel tabModel = (DefaultTableModel)table.getModel();
                tabModel.addRow(tabData);
            
            }
            
            stmt.close();
            rs.close();
            conn.close();
        }
        catch(SQLException e){
            System.out.println("erreur "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ldate_mes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lname_sen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        llastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lnum_sen = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        testMsg = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenue dans l'espace des messages");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 30, 370, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date of Messge :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 120, 30);
        getContentPane().add(ldate_mes);
        ldate_mes.setBounds(120, 80, 170, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 80, 30);

        lname_sen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lname_sen);
        lname_sen.setBounds(120, 120, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 160, 90, 30);

        llastname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(llastname);
        llastname.setBounds(120, 160, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("E-mail  :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 200, 70, 30);
        getContentPane().add(lemail);
        lemail.setBounds(120, 200, 170, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone Number :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 240, 100, 30);

        lnum_sen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lnum_sen);
        lnum_sen.setBounds(120, 240, 170, 30);

        jButton1.setBackground(new java.awt.Color(250, 128, 114));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Click to Delete Messge");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 280, 260, 40);

        table.setForeground(new java.awt.Color(102, 0, 51));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date of message", "First Name sender", "Last Name sender", "E-mail sender"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 80, 490, 190);

        testMsg.setColumns(20);
        testMsg.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        testMsg.setRows(5);
        jScrollPane3.setViewportView(testMsg);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 320, 520, 170);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Message:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 280, 90, 30);

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(700, 450, 110, 40);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ucaa.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 820, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JDBC db=new JDBC();
        db.connection();
        int r = table.getSelectedRow();
        r=r+1;
        String msg = testMsg.getText();
        String dateM = ldate_mes.getText();

        try {
            if(r!=0){
                System.out.println(r);
                String sqll = "DELETE FROM message WHERE TEXT_MES='"+msg+"'";
                stmt.executeUpdate(sqll);
                //actualiser
            }
            this.setVisible(false);
            new affiche_messages().setVisible(true);
        }
        catch (SQLException ex){
            System.out.println("Erreur1"+ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int r = table.getSelectedRow();
        String email=table.getModel().getValueAt(r, 3).toString();
        //System.out.println(r);
        JDBC db=new JDBC();
        db.connection();
        String sql="SELECT * FROM MESSAGE m,SENDER s WHERE m.ID_SEN=s.ID_SEN and s.EMAIL_SEN='"+email+"'";
        try {
            rs=stmt.executeQuery(sql);
            while(rs.next()){
                //System.out.println(rs.getString("TEXT_MES"));
                testMsg.setText(rs.getString("TEXT_MES"));
                String[] a = rs.getString("DATE_MES").split(" ", 2);
                //System.out.println(a[0]);
                ldate_mes.setText(a[0]);
                lname_sen.setText(rs.getString("PRENOM_SEN"));
                llastname.setText(rs.getString("NOM_SEN"));
                lemail.setText(rs.getString("EMAIL_SEN"));
                lnum_sen.setText(rs.getString("TELE_SEN"));
            }
            rs.close();
            stmt.close();
            conn.close();
        }
        catch (SQLException ex) {
            System.out.println("erreur"+ex);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int response= JOptionPane.showConfirmDialog(null, "Do you really want to Quit?", "Confirm",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response== JOptionPane.NO_OPTION) {
            new affiche_messages().setVisible(false);
        } else if (response== JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(affiche_messages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(affiche_messages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(affiche_messages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(affiche_messages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new affiche_messages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField ldate_mes;
    private javax.swing.JTextField lemail;
    private javax.swing.JTextField llastname;
    private javax.swing.JTextField lname_sen;
    private javax.swing.JTextField lnum_sen;
    private javax.swing.JTable table;
    private javax.swing.JTextArea testMsg;
    // End of variables declaration//GEN-END:variables
}
